[[language]]
name="rust"
formatter = { command = "rustfmt" }
auto-format = true

[[language]]
name="python"
formatter = {command = 'black', args = ["--quiet", "-"]}
auto-format = true

[[language]]
name="c"
formatter = { command = "clang-format-16" }
auto-format = true

[language-server.rust-analyzer.config]
checkOnSave = {command = "clippy", extraArgs = ["--", "-W", "clippy::pedantic"]}
cargo = {allFeatures = true}
procMacro = {enable = true }
